# generated by claude.ai
# TODO modularise
# also there is an open issue in sysm to add desktop manager modules
{
  pkgs,
  ...
}:
let
  DISPLAY = ":99";
in
{
  config = {
    environment.systemPackages = with pkgs; [
      x11vnc
      xorg.xvfb
      fluxbox
    ];

    systemd.services.xvfb = {
      enable = true;
      description = "Virtual X Server";
      serviceConfig = {
        Type = "simple";
        ExecStart = "${pkgs.xorg.xvfb}/bin/Xvfb ${DISPLAY} -screen 0 1024x768x24 -ac +extension GLX +render -noreset";
        Restart = "always";
      };
      wantedBy = [ "system-manager.target" ];
    };

    systemd.services.fluxbox = {
      enable = true;
      description = "Fluxbox Window Manager";
      after = [ "xvfb.service" ];
      requires = [ "xvfb.service" ];
      environment.DISPLAY = DISPLAY;
      serviceConfig = {
        Type = "simple";
        ExecStart = "${pkgs.fluxbox}/bin/fluxbox";
        Restart = "always";
      };
      wantedBy = [ "system-manager.target" ];
    };

    systemd.services.x11vnc = {
      enable = true;
      description = "VNC Server";
      after = [ "xvfb.service" ];
      requires = [ "xvfb.service" ];
      serviceConfig = {
        Type = "simple";
        ExecStart = "${pkgs.x11vnc}/bin/x11vnc -display ${DISPLAY} -forever -nopw -shared -rfbport 5900";
        Restart = "always";
      };
      wantedBy = [ "system-manager.target" ];
    };
  };
}
