# Generated by claude.ai
{ lib, ... }:
{
  # BIGGEST WINS - Save ~12+ seconds:

  # 1. NetworkManager-wait-online (4.3s saved)
  #systemd.services.NetworkManager-wait-online.enable = false;
  systemd.services.NetworkManager-wait-online.wantedBy = lib.mkForce [ ];

  # 2. systemd-tmpfiles-clean (4.3s saved) - only runs periodically, not every boot
  systemd.services.systemd-tmpfiles-clean = {
    unitConfig.ConditionNeedsUpdate = "/var";
  };

  # 3. fwupd (2.6s saved) - firmware updates, rarely needed at boot
  services.fwupd.enable = true; # Keep it installed
  systemd.services.fwupd.wantedBy = lib.mkForce [ ]; # Don't start at boot

  # 4. Docker (2.1s saved) - start on-demand
  systemd.services.docker.wantedBy = lib.mkForce [ ];
  systemd.services.docker.after = [ "multi-user.target" ];
  virtualisation.docker.enableOnBoot = lib.mkForce false;

  # 5. Firewall (2.0s saved) - optimize
  networking.firewall = {
    checkReversePath = "loose";
    # Or if you don't need firewall:
    # enable = false;
  };

  # CRITICAL FIX - Disable unused serial ports (saves ~5.7s!)
  # Not really, doesn't save jack, as its not in the critical chain
  boot.kernelParams = [
    "8250.nr_uarts=0" # Disable legacy serial ports entirely
  ];
  # Also disable in kernel config:
  boot.blacklistedKernelModules = [ "serial8250" ];

  # MEDIUM WINS:

  # 6. systemd-binfmt (1.3s) - only if you don't use cross-arch execution
  # boot.binfmt.emulatedSystems = lib.mkForce [ ]; # If you don't need this

  # 7. Reduce module load time (4.5s)
  # boot.initrd.systemd.enable = true; # Modern faster init
  # Didn't help, made the overall time +3s

  # 8. Services you may not need at boot:
  systemd.services.plex.wantedBy = lib.mkForce [ ]; # Start manually
  systemd.services.libvirtd.wantedBy = lib.mkForce [ ]; # Start when needed

  # xfce might need these two
  # Make them start AFTER your desktop is up (not blocking boot)
  systemd.services.udisks2.wantedBy = lib.mkForce [ ]; # 219ms - USB disk mounting
  systemd.services.accounts-daemon.wantedBy = lib.mkForce [ ]; # 574ms

  # Enable them on-demand when XFCE needs them
  systemd.services.udisks2.serviceConfig.Type = "dbus";
  systemd.services.accounts-daemon.serviceConfig.Type = "dbus";
}
